/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Manyor
 */
public class IMAX extends javax.swing.JFrame {

    /**
     * Creates new form IMAX
     */
    public IMAX() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuPeliculas = new javax.swing.JMenuItem();
        mnuSalas = new javax.swing.JMenuItem();
        mnuTandas = new javax.swing.JMenuItem();
        mnuProgramacion = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/promos.jpg"))); // NOI18N

        jMenu1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu1.setText("Mantenimientos");

        mnuPeliculas.setText("Mantenimiento Peliculas");
        mnuPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPeliculasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuPeliculas);

        mnuSalas.setText("Mantenimiento Salas");
        mnuSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSalas);

        mnuTandas.setText("Mantenimiento Tandas");
        mnuTandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTandasActionPerformed(evt);
            }
        });
        jMenu1.add(mnuTandas);

        mnuProgramacion.setText("Mantenimiento Programación");
        mnuProgramacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuProgramacionMouseClicked(evt);
            }
        });
        jMenu1.add(mnuProgramacion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalasActionPerformed
        frmSalas win = new frmSalas(null, true);
        win.setVisible(true);
    }//GEN-LAST:event_mnuSalasActionPerformed

    private void mnuPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPeliculasActionPerformed
        // TODO add your handling code here:
        frmPeliculas win = new frmPeliculas(null, true);
        win.setVisible(true);
    }//GEN-LAST:event_mnuPeliculasActionPerformed

    private void mnuTandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTandasActionPerformed
        // TODO add your handling code here:
        frmTandas win= new frmTandas(null, true);
        win.setVisible(true);
    }//GEN-LAST:event_mnuTandasActionPerformed

    private void mnuProgramacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuProgramacionMouseClicked
        // TODO add your handling code here:
        frmAgregaProgramacion win = new frmAgregaProgramacion(null, true);
         win.setVisible(true);
    }//GEN-LAST:event_mnuProgramacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMAX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuPeliculas;
    private javax.swing.JMenu mnuProgramacion;
    private javax.swing.JMenuItem mnuSalas;
    private javax.swing.JMenuItem mnuTandas;
    // End of variables declaration//GEN-END:variables
}
