/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Datos.DatosPelicula;
import Datos.DatosProgramacion;
import Datos.DatosSala;
import Datos.DatosTanda;

/**
 *
 * @author Manyor
 */
public class IMAX extends javax.swing.JFrame {

    DatosPelicula almacenaPeli = new DatosPelicula(20);
    DatosSala almacenaSala= new DatosSala(20);
    DatosTanda almacTanda=new DatosTanda(20);
    DatosProgramacion almacProgra=new DatosProgramacion(20);

    /**
     * Creates new form IMAX
     */
    public IMAX() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuProgramacion = new javax.swing.JMenu();
        mnuPeliculas = new javax.swing.JMenuItem();
        mnuSalas = new javax.swing.JMenuItem();
        mnuTandas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setForeground(new java.awt.Color(0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1600, 919));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ba_1.jpg"))); // NOI18N

        mnuProgramacion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mnuProgramacion.setText("Mantenimientos");

        mnuPeliculas.setText("Mantenimiento Peliculas");
        mnuPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPeliculasActionPerformed(evt);
            }
        });
        mnuProgramacion.add(mnuPeliculas);

        mnuSalas.setText("Mantenimiento Salas");
        mnuSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalasActionPerformed(evt);
            }
        });
        mnuProgramacion.add(mnuSalas);

        mnuTandas.setText("Mantenimiento Tandas");
        mnuTandas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTandasActionPerformed(evt);
            }
        });
        mnuProgramacion.add(mnuTandas);

        jMenuItem2.setText("Mantenimiento Programación");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        mnuProgramacion.add(jMenuItem2);

        jMenuBar1.add(mnuProgramacion);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalasActionPerformed
        frmSalas win = new frmSalas(null, true,almacenaSala);
        win.setVisible(true);
    }//GEN-LAST:event_mnuSalasActionPerformed

    private void mnuPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPeliculasActionPerformed
        // TODO add your handling code here:
        frmPeliculas win = new frmPeliculas(null, true, almacenaPeli);
        win.setVisible(true);
    }//GEN-LAST:event_mnuPeliculasActionPerformed

    private void mnuTandasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTandasActionPerformed
        // TODO add your handling code here:
        frmTandas win = new frmTandas(null, true,almacTanda);
        win.setVisible(true);
    }//GEN-LAST:event_mnuTandasActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        frmProgramacion win = new frmProgramacion(null, true,almacProgra,almacenaPeli,almacenaSala,almacTanda);
        win.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IMAX.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IMAX().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mnuPeliculas;
    private javax.swing.JMenu mnuProgramacion;
    private javax.swing.JMenuItem mnuSalas;
    private javax.swing.JMenuItem mnuTandas;
    // End of variables declaration//GEN-END:variables
}
